streamline
wisemen-digital/frontend-project-template pull request #16
Opened 2024-02-22 10:47 UTC by wouterlms

2024-02-22 10:52 UTC, maltsavkiryl commented on src/plugins/sentry/sentry.plugin.ts
> +const { VITE_SENTRY_DSN, VITE_ENVIRONMENT, VITE_SENTRY_SAMPLE_RATE, VITE_APP_VERSION } = import.meta.env
dit moeten we aanpassen zoals het in Studaro en IN-Z staat.

Die VITE_ prefix werkt niet meer. Ik kan dat ook wel aanpassen als je wilt, laat maar weten :)

2024-02-22 10:53 UTC, maltsavkiryl commented on src/plugins/sentry/sentry.plugin.ts
> +const { VITE_SENTRY_DSN, VITE_ENVIRONMENT, VITE_SENTRY_SAMPLE_RATE, VITE_APP_VERSION } = import.meta.env
Spreading werkte ook niet, dan moet dan effectief  op deze manier geschreven zijn:

```typescript
environment: import.meta.env.ENVIRONMENT,
```

2024-02-23 16:33 UTC, wouterlms commented on src/components/app/error-state/AppErrorState.vue
> +logError(props.message)
Ja, anders krijg je de foutmelding nooit te zien in je console en heb je geen idee wat er fout loopt

2024-02-24 13:36 UTC, maltsavkiryl commented on src/components/app/error-state/AppErrorState.vue
> +logError(props.message)
Gucci

2024-02-24 17:49 UTC, wouterlms commented on src/modules/auth/features/forgot-password/views/AuthForgotPasswordView.vue
> +		useHandleApiError(error, form)
Dat zit momenteel in `useHandleApiError`

2024-02-25 14:50 UTC, maltsavkiryl commented on src/modules/auth/features/forgot-password/views/AuthForgotPasswordView.vue
> +		useHandleApiError(error, form)
lijkt voor mij beter als we dat opsplitsen en het specifiek op de toast een error pushen en daarnaast de errors op de form zouden applyen. Nu zit dat onnodig hidden en gemengd IMHO

2024-02-28 09:04 UTC, JeffreyNijs requested changes

2024-02-28 09:04 UTC, JeffreyNijs commented on src/modules/users/features/detail/views/UsersDetailViewDataProvider.vue
> +		v-if="user !== null"
Waarom doen we `user !== null` als we ook gwn `user` kunnen doen? Ik zie dat op meerdere plekken zo staan, maar ik zou het toch iets meer generisch houden en bv undefined ook afblokken.

2024-02-28 09:04 UTC, JeffreyNijs commented on src/types/query/queryKey.type.ts
> +	// Users
Waarom staat hier twee keer // Users gecomment met een whitespace?

2024-02-28 09:04 UTC, JeffreyNijs commented on vite.config.ts
> +// import VueDevTools from 'vite-plugin-vue-devtools'
Waarom comment?

2024-02-28 12:32 UTC, wouterlms commented on src/modules/users/api/services/user.service.ts
> +			total: 200,
Enkel omdat die test api niet teruggeeft hoeveel items er in totaal zijn

2024-02-28 12:34 UTC, wouterlms commented on src/components/app/table/AppTable.vue
> +	await nextTick()
Ja omdat de dom nog gewijzigd moet worden

2024-02-28 12:36 UTC, wouterlms commented on src/components/app/table/AppTable.vue
> +watch(() => props.data, onDataChange)
Wanneer de data changed moet er gekeken worden of het scrollable is enzo (voor pinned columns). Als jij een betere manier weet mag je het aanpassen, ik weet niet hoe ik dit anders kan schrijven

2024-02-28 12:37 UTC, wouterlms commented on src/components/app/table/AppTableFooter.vue
> +	const { page, perPage } = props.paginationOptions.pagination
Ik vind dit veel duidelijker dan `return Math.min(props.paginationOptions.pagination.perPage * (props.paginationOptions.pagination.page + 1), props.total)` nee?

2024-02-28 12:43 UTC, wouterlms commented on src/modules/auth/features/forgot-password/views/AuthForgotPasswordView.vue
> +onSubmitForm(async (values) => {
Zo'n dingen zijn perfect duidelijk destructuren en dan moet je niet `form.form` gebruiken

2024-02-28 12:44 UTC, wouterlms commented on src/modules/users/api/mutations/userUpdate.mutation.ts
> +		queryKeysToInvalidate: [
Improved typing, ik kan dat ook op ongeveer dezelfde manier doen

2024-02-28 12:45 UTC, wouterlms commented on src/modules/users/features/detail/views/UsersDetailViewDataProvider.vue
> +		v-if="user !== null"
Dit kan niet `undefined` zijn. En de plaatsen waar `if(user)` staat heb ik niet zelf geschreven. Dit is ook geen best practice. Een conditional moet altijd een boolean bevatten, niets anders

2024-02-28 12:46 UTC, wouterlms commented on src/types/query/queryKey.type.ts
> +	// Users
Leesbaarheid wanneer het meer wordt

2024-02-28 12:54 UTC, wouterlms commented on src/components/app/table/AppTableTextCell.vue
> +import AppText from '../text/AppText.vue'
Gebeurt automatisch bij mij

2024-02-28 13:15 UTC, maltsavkiryl approved these changes
LETS FOOOKING GO 🚀

2024-02-28 13:23 UTC, merged