migrate to core library + small improvements
wisemen-digital/frontend-project-template pull request #29
Opened 2024-03-28 09:03 UTC by wouterlms

2024-03-28 09:17 UTC, maltsavkiryl requested changes
Looks great mate 🚀 Nog een paar kleine remarks

2024-03-28 09:17 UTC, maltsavkiryl commented on package.json
> +    "@tanstack/vue-query": "5.22.2",
version downgrade?

2024-03-28 09:17 UTC, maltsavkiryl commented on package.json
> +    "@appwise/eslint-config-vue": "1.2.2",
moet deze niet weg?

2024-03-28 09:17 UTC, maltsavkiryl commented on src/components/dialogs/AppConfirmDialog.vue
> +          This action cannot be undone.
moet dit niet `{{ props.description }}` zijn?

2024-03-28 09:17 UTC, maltsavkiryl commented on src/components/dialogs/AppConfirmDialog.vue
> +        Ok
translation toevoegen en eventueel ook een optional prop

2024-03-28 09:18 UTC, maltsavkiryl commented on src/libs/http.lib.ts
> +      title: 'Something went wrong',
mss ook een translation

2024-03-28 09:18 UTC, maltsavkiryl commented on src/modules/users/api/queries/usersIndex.query.ts
> +      // params: usePaginationOptionsToApiParams(paginationOptions),
commented code

2024-03-28 09:30 UTC, Robbe95 requested changes

2024-03-28 09:30 UTC, Robbe95 commented on src/components/app/AppSearchInput.vue
> +          Clear
Deze dingen moeten nog in een translation denk ik?

2024-03-28 09:30 UTC, Robbe95 commented on src/components/dialogs/AppConfirmDialog.vue
> +          This action cannot be undone.
Translate!

2024-03-28 09:30 UTC, Robbe95 commented on src/components/dialogs/AppConfirmDialog.vue
> +        Ok
Ook deze aub

2024-03-28 09:30 UTC, Robbe95 commented on src/components/form/form/AppFormSubmitButton.vue
> +  disabledKeyboardCommand?: boolean
boolean met is / has prefixen

2024-03-28 09:30 UTC, Robbe95 commented on src/components/layout/AppDarkModeToggle.vue
> +      :icon="props.isDarkMode
Misschien logica in computed in script steken

2024-03-28 09:30 UTC, Robbe95 commented on src/modules/users/api/services/user.service.ts
> +      data: data.items.map(transformUserIndexDtoToUserIndex),
Niet voor dit maar misschien een paginated data response transformer functie maken?

2024-03-28 09:30 UTC, Robbe95 commented on src/modules/users/features/overview/components/UsersOverviewTable.vue
> +    :row-to="(row) => ({
functie in script zetten

2024-03-28 10:27 UTC, wouterlms commented on src/components/form/form/AppFormSubmitButton.vue
> +  disabledKeyboardCommand?: boolean
Dat gaat bij zoiets toch niet? En ik vind `shouldDisableKeyboardCommand` mottig

2024-03-28 15:04 UTC, wouterlms commented on src/modules/users/features/overview/components/UsersOverviewTable.vue
> +    :row-to="(row) => ({
Denk niet dat dat per se nodig is, bij een normale routerlink doen we dat ook niet

2024-03-28 15:05 UTC, Robbe95 commented on src/modules/users/features/overview/components/UsersOverviewTable.vue
> +    :row-to="(row) => ({
:O

2024-03-28 17:56 UTC, maltsavkiryl commented on src/modules/users/features/overview/components/UsersOverviewTable.vue
> +    :row-to="(row) => ({
yeah weet ook niet zo goed of het de moeite is om dat in de script te zetten 🤷‍♂️ heb zelf geen voorkeur

2024-03-30 14:22 UTC, wouterlms commented on src/libs/http.lib.ts
> +      title: 'Something went wrong',
In productie wordt dit niet gebruikt

2024-04-01 10:46 UTC, maltsavkiryl approved these changes

2024-04-01 10:50 UTC, merged